// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TYPES_SELFMESSAGING_H_
#define FLATBUFFERS_GENERATED_TYPES_SELFMESSAGING_H_

#include "flatbuffers/flatbuffers.h"

namespace SelfMessaging {

enum ACLCommand {
  ACLCommand_LIST = 0,
  ACLCommand_PERMIT = 1,
  ACLCommand_REVOKE = 2,
  ACLCommand_MIN = ACLCommand_LIST,
  ACLCommand_MAX = ACLCommand_REVOKE
};

inline const ACLCommand (&EnumValuesACLCommand())[3] {
  static const ACLCommand values[] = {
    ACLCommand_LIST,
    ACLCommand_PERMIT,
    ACLCommand_REVOKE
  };
  return values;
}

inline const char * const *EnumNamesACLCommand() {
  static const char * const names[4] = {
    "LIST",
    "PERMIT",
    "REVOKE",
    nullptr
  };
  return names;
}

inline const char *EnumNameACLCommand(ACLCommand e) {
  if (flatbuffers::IsOutRange(e, ACLCommand_LIST, ACLCommand_REVOKE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesACLCommand()[index];
}

enum ErrType {
  ErrType_ErrConnection = 0,
  ErrType_ErrBadRequest = 1,
  ErrType_ErrInternal = 2,
  ErrType_ErrMessage = 3,
  ErrType_ErrAuth = 4,
  ErrType_ErrACL = 5,
  ErrType_MIN = ErrType_ErrConnection,
  ErrType_MAX = ErrType_ErrACL
};

inline const ErrType (&EnumValuesErrType())[6] {
  static const ErrType values[] = {
    ErrType_ErrConnection,
    ErrType_ErrBadRequest,
    ErrType_ErrInternal,
    ErrType_ErrMessage,
    ErrType_ErrAuth,
    ErrType_ErrACL
  };
  return values;
}

inline const char * const *EnumNamesErrType() {
  static const char * const names[7] = {
    "ErrConnection",
    "ErrBadRequest",
    "ErrInternal",
    "ErrMessage",
    "ErrAuth",
    "ErrACL",
    nullptr
  };
  return names;
}

inline const char *EnumNameErrType(ErrType e) {
  if (flatbuffers::IsOutRange(e, ErrType_ErrConnection, ErrType_ErrACL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesErrType()[index];
}

enum MsgType {
  MsgType_MSG = 0,
  MsgType_ACK = 1,
  MsgType_ERR = 2,
  MsgType_AUTH = 3,
  MsgType_ACL = 4,
  MsgType_MIN = MsgType_MSG,
  MsgType_MAX = MsgType_ACL
};

inline const MsgType (&EnumValuesMsgType())[5] {
  static const MsgType values[] = {
    MsgType_MSG,
    MsgType_ACK,
    MsgType_ERR,
    MsgType_AUTH,
    MsgType_ACL
  };
  return values;
}

inline const char * const *EnumNamesMsgType() {
  static const char * const names[6] = {
    "MSG",
    "ACK",
    "ERR",
    "AUTH",
    "ACL",
    nullptr
  };
  return names;
}

inline const char *EnumNameMsgType(MsgType e) {
  if (flatbuffers::IsOutRange(e, MsgType_MSG, MsgType_ACL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMsgType()[index];
}

enum MsgSubType {
  MsgSubType_Unknown = 0,
  MsgSubType_AuthenticationReq = 1,
  MsgSubType_AuthenticationResp = 2,
  MsgSubType_AuthenticationQRResp = 3,
  MsgSubType_AuthenticationDeepLinkResp = 4,
  MsgSubType_FactReq = 5,
  MsgSubType_FactResp = 6,
  MsgSubType_FactQRResp = 7,
  MsgSubType_FactDeepLinkResp = 8,
  MsgSubType_EmailSecurityCodeReq = 9,
  MsgSubType_EmailSecurityCodeResp = 10,
  MsgSubType_PhoneSecurityCodeReq = 11,
  MsgSubType_PhoneSecurityCodeResp = 12,
  MsgSubType_PhoneVerificationReq = 13,
  MsgSubType_PhoneVerificationResp = 14,
  MsgSubType_EmailVerificationReq = 15,
  MsgSubType_EmailVerificationResp = 16,
  MsgSubType_DocumentVerificationReq = 17,
  MsgSubType_DocumentVerificationResp = 18,
  MsgSubType_MIN = MsgSubType_Unknown,
  MsgSubType_MAX = MsgSubType_DocumentVerificationResp
};

inline const MsgSubType (&EnumValuesMsgSubType())[19] {
  static const MsgSubType values[] = {
    MsgSubType_Unknown,
    MsgSubType_AuthenticationReq,
    MsgSubType_AuthenticationResp,
    MsgSubType_AuthenticationQRResp,
    MsgSubType_AuthenticationDeepLinkResp,
    MsgSubType_FactReq,
    MsgSubType_FactResp,
    MsgSubType_FactQRResp,
    MsgSubType_FactDeepLinkResp,
    MsgSubType_EmailSecurityCodeReq,
    MsgSubType_EmailSecurityCodeResp,
    MsgSubType_PhoneSecurityCodeReq,
    MsgSubType_PhoneSecurityCodeResp,
    MsgSubType_PhoneVerificationReq,
    MsgSubType_PhoneVerificationResp,
    MsgSubType_EmailVerificationReq,
    MsgSubType_EmailVerificationResp,
    MsgSubType_DocumentVerificationReq,
    MsgSubType_DocumentVerificationResp
  };
  return values;
}

inline const char * const *EnumNamesMsgSubType() {
  static const char * const names[20] = {
    "Unknown",
    "AuthenticationReq",
    "AuthenticationResp",
    "AuthenticationQRResp",
    "AuthenticationDeepLinkResp",
    "FactReq",
    "FactResp",
    "FactQRResp",
    "FactDeepLinkResp",
    "EmailSecurityCodeReq",
    "EmailSecurityCodeResp",
    "PhoneSecurityCodeReq",
    "PhoneSecurityCodeResp",
    "PhoneVerificationReq",
    "PhoneVerificationResp",
    "EmailVerificationReq",
    "EmailVerificationResp",
    "DocumentVerificationReq",
    "DocumentVerificationResp",
    nullptr
  };
  return names;
}

inline const char *EnumNameMsgSubType(MsgSubType e) {
  if (flatbuffers::IsOutRange(e, MsgSubType_Unknown, MsgSubType_DocumentVerificationResp)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMsgSubType()[index];
}

}  // namespace SelfMessaging

#endif  // FLATBUFFERS_GENERATED_TYPES_SELFMESSAGING_H_
